<?php 
function st_material_type_permission(){
array (
  'st_material_type_per_add' => 
  array (
    'title' => 'Create form st_material_type According To choice',
    'description' => 'Form st_material_type Creation',
  ),
  'st_material_type_per_view' => 
  array (
    'title' => 'View The List Of st_material_type',
    'description' => 'View st_material_type according to his powers',
  ),
);
}
function st_material_type_menu() {
$items['admins/st_material_type/add']=array (
  'title' => 'Add New St Material Type Form',
  'page callback' => 'drupal_get_form',
  'page arguments' => 
  array (
    0 => 'st_material_type_add',
  ),
  'access arguments' => 
  array (
    0 => 'st_material_type_per_add',
  ),
  'description' => 'General',
  'type' => 0,
  'weight' => 1,
);
$items['admins/st_material_type/view']=array (
  'title' => 'St Material Type List',
  'page callback' => 'drupal_get_form',
  'page arguments' => 
  array (
    0 => 'st_material_type_view',
  ),
  'access arguments' => 
  array (
    0 => 'st_material_type_per_view',
  ),
  'description' => 'General',
  'type' => 0,
  'weight' => 1,
);
$items['admins/st_material_type/edit/%']=array (
  'title' => 'St Material Type Edit',
  'page callback' => 'drupal_get_form',
  'page arguments' => 
  array (
    0 => 'st_material_type_add',
    1 => 3,
  ),
  'access arguments' => 
  array (
    0 => 'st_material_type_per_add',
  ),
  'description' => 'General',
  'type' => 0,
  'weight' => 1,
);
$items['admins/st_material_type/detail/%']=array (
  'title' => 'St Material Type detail',
  'page callback' => 'drupal_get_form',
  'page arguments' => 
  array (
    0 => 'st_material_type_detail',
    1 => 3,
  ),
  'access arguments' => 
  array (
    0 => 'st_material_type_per_view',
  ),
  'description' => 'General',
  'type' => 0,
  'weight' => 1,
);
return $items;
}
function st_material_type_add($form,&$form_state,$id=NULL){
	//material_status();
	//exit;
if(!empty($id)){
		$data = get_data_by_pks('st_material_type', $id);
		
		$form['#submit'][] = "st_material_type_edit_submit";
		$form['id']=array(
				'#type'=>'value',
				'#value'=>$id,
		);
	}	
$form['m_id']=array (
  '#type' => 'select',
  '#title' => 'Material Name',
  '#options' =>material_status(),
  '#attributes' => 
  array (
    'placeholder' => '',
  ),
  '#default_value' => isset($data->m_id)?$data->m_id:"",
);
$form['m_type']=array (
  '#type' => 'textfield',
  '#title' => 'Material SubCategory',
  '#size' => '255',
  '#attributes' => 
  array (
    'placeholder' => '',
    'maxlength' => '255',
  ),
  '#default_value' => isset($data->m_type)?$data->m_type:"",
);
$form['m_value']=array (
  '#type' => 'textfield',
  '#title' => 'Material value',
  '#size' => '255',
  '#attributes' => 
  array (
    'placeholder' => '',
    'maxlength' => '255',
  ),
  '#default_value' => isset($data->m_value)?$data->m_value:"",
);
$form['m_unit']=array (
  '#type' => 'select',
  '#title' => 'Material unit',
  
	'#options'=>units(),
  '#attributes' => 
  array (
  
  ),
  '#default_value' => isset($data->m_unit)?$data->m_unit:"",
);

$form['submit']=array('#type'=>'submit','#value'=>'Save');
return $form;
}
function st_material_type_validate($form,&$form_state){

}
function st_material_type_add_submit($form,&$form_state){
global $user;
$query = db_insert('st_material_type')
	 ->fields(array('m_id'=>$form_state['values']['m_id'],
	 		'm_type'=>$form_state['values']['m_type'],
	 		'm_value'=>$form_state['values']['m_value'],
	 		'm_unit'=>$form_state['values']['m_unit'],
	 		'created'=>time(),
	 )
	 		)->execute();
if($query>0){
    	drupal_set_message('st_material_type added successfully');
		drupal_goto('admins/st_material_type/view');	
    }
}
function st_material_type_edit_submit($form,&$form_state){
global $user;
$query = db_update('st_material_type')
	 ->fields(array('m_id'=>$form_state['values']['m_id'],'m_type'=>$form_state['values']['m_type'],'m_value'=>$form_state['values']['m_value'],'m_unit'=>$form_state['values']['m_unit'],'created'=>strtotime($form_state['values']['created']),'updated'=>strtotime($form_state['values']['updated']),'updatedby'=>$form_state['values']['updatedby'],'createdby'=>$form_state['values']['createdby'],))
	 ->condition('id', $form_state['values']['id'], '=')
	 ->execute();
if($form_state['values']['id']>0){
    	drupal_set_message('st_material_type update successfully');
		drupal_goto('admins/st_material_type/view');
    }
}
function st_material_type_view($form,&$form_state){
global $user;
	$query = db_select('st_material_type','tn')
	->extend('PagerDefault')
	->fields('tn')
	->orderBy('tn.id','desc')
	->limit(20);
	$result = $query->execute();
$rows_articles=array();
foreach ($result as $records){
//$created=util_date_format_short($records->created);
//$updated=util_date_format_short($records->updated);
/*if($records->deleted){
			 $deleted="Deleted";
            }
		else
		{
			//$deleted=l("<i class='icon-fixed-width icon-trash'></i>Delete",'admins/st_material_type/edit/'.$records->id,array('html'=>TRUE));
		}*/
	$material_name=material_name($records->m_id);
$rows_articles[] = array(l($records->id,'st_material_type/edit/'.$records->id),$material_name,$records->m_type,$records->m_value,$records->m_unit,$records->created,$records->updated,$records->updatedby,$records->createdby,);
}
$headers=array('Id','Material Name','Material type','Material value','Material unit','Created','Updated','Updatedby','Createdby',);
$all_articles=theme('table', array('header' => $headers, 'rows' => $rows_articles,'empty'=>'No Record Found','attributes'=>array('class'=>array('list-table'),'style'=>'width:100%;')));
$all_articles .=theme('pager');
$form['all_articles']=array(
			'#markup'=>$all_articles,
	);
return $form;
}
function st_material_type_detail($form,&$form_state,$id=NULL){
global $user;
	$query = db_select('st_material_type','tn')
	->extend('PagerDefault')
	->fields('tn')
	->condition('tn.id',$id,'=')
	->orderBy('tn.id','desc');
	$result = $query->execute()->fetchObject();
$rows_articles=array();
if(!empty($result))
foreach ($result as $key => $value){

$rows_articles[] = array($key.' :: '.$value);
}

$all_articles=theme('table', array('header' => array(), 'rows' => $rows_articles,'empty'=>'No Record Found','attributes'=>array('class'=>array('list-table'),'style'=>'width:100%;')));
$all_articles .=theme('pager');
$form['all_articles']=array(
			'#markup'=>$all_articles,
	);
return $form;
}
function material_status(){
	$mat=array();
	$result=db_query("SELECT material_name from st_material")->fetchAll();
	
 	foreach($result as $res){
		
 		 $mat[0]='Select';
		 $mat[]=$res->material_name;
		//$mat[]=$res->id;
		//$res=$res->id;
	} 
	return $mat;
}
function material_name($id){
	
	$result=db_query("SELECT material_name from st_material where id=$id")->fetchAll();
	return $result[0]->material_name;
}

/*function get_data($id,$tablename,$field){
	
	$result=db_query("SELECT $field from $tablename where id=$id")->fetchAll();
	return $result;
	
}*/
	
function units(){
	
	$units=array(
			'0'=>'Select Unit',
			'1'=>'Kg',
			'2'=>'Quintal',
				
	);
	return $units;
}