<?php 
function st_price_permission(){
array (
  'st_price_per_add' => 
  array (
    'title' => 'Create form st_price According To choice',
    'description' => 'Form st_price Creation',
  ),
  'st_price_per_view' => 
  array (
    'title' => 'View The List Of st_price',
    'description' => 'View st_price according to his powers',
  ),
);
}
function st_price_menu() {
$items['admins/st_price/add']=array (
  'title' => 'Add New St Price Form',
  'page callback' => 'drupal_get_form',
  'page arguments' => 
  array (
    0 => 'st_price_add',
  ),
  'access arguments' => 
  array (
    0 => 'st_price_per_add',
  ),
  'description' => 'General',
  'type' => 0,
  'weight' => 1,
);
$items['admins/st_price/view']=array (
  'title' => 'St Price List',
  'page callback' => 'drupal_get_form',
  'page arguments' => 
  array (
    0 => 'st_price_view',
  ),
  'access arguments' => 
  array (
    0 => 'st_price_per_view',
  ),
  'description' => 'General',
  'type' => 0,
  'weight' => 1,
);
$items['admins/st_price/edit/%']=array (
  'title' => 'St Price Edit',
  'page callback' => 'drupal_get_form',
  'page arguments' => 
  array (
    0 => 'st_price_add',
    1 => 3,
  ),
  'access arguments' => 
  array (
    0 => 'st_price_per_add',
  ),
  'description' => 'General',
  'type' => 0,
  'weight' => 1,
);
$items['admins/st_price/detail/%']=array (
  'title' => 'St Price detail',
  'page callback' => 'drupal_get_form',
  'page arguments' => 
  array (
    0 => 'st_price_detail',
    1 => 3,
  ),
  'access arguments' => 
  array (
    0 => 'st_price_per_view',
  ),
  'description' => 'General',
  'type' => 0,
  'weight' => 1,
);
return $items;
}
function st_price_add($form,&$form_state,$id=NULL){
	drupal_add_js ( 'misc/user_validation.js', 'file' );
	
if(!empty($id)){
		$data = get_data_by_pks('st_price', $id);
		
		$form['#submit'][] = "st_price_edit_submit";
		$form['id']=array(
				'#type'=>'value',
				'#value'=>$id,
		);
	}	
$form['mid']=array (
  '#type' => 'select',
  '#title' => 'Mid',
  '#options' => ut_material_inventery(),
  '#attributes' => 
  array (
    'placeholder' => '',
  ),
  '#default_value' => isset($data->mid)?$data->mid:"",
);
$form['unit_prices']=array (
		'#type' => 'textfield',
		'#title' => 'Unit Prices',
		'#size' => '255',
		'#attributes' =>
		array (
				'placeholder' => '',
				'maxlength' => '255',
		),
		'#default_value' => isset($data->unit_price)?$data->unit_price:"",
		'#ajax' => array(
				'callback' => 'ajax_example_autocheckboxes_callback1',
				'wrapper' => 'checkboxes-div',
				'method' => 'replace',
				'effect' => 'fade',
		),
);
$form['total_price']=array (
		'#type' => 'textfield',
		'#title' => 'Total Price',
		'#size' => '255',
		'#attributes' =>
		array (
				'placeholder' => '',
				'maxlength' => '255',
		),
		'#default_value' => isset($data->total_price)?$data->total_price:"",
);
$form['base_price']=array (
		'#type' => 'textfield',
		'#title' => 'Base price',
		'#size' => '255',
		'#attributes' =>
		array (
				'placeholder' => '',
				'maxlength' => '255',
		),
		'#default_value' => isset($data->base_price)?$data->base_price:"",
);
$form['sale_price']=array (
		'#type' => 'textfield',
		'#title' => 'Sale Price',
		'#size' => '255',
		'#attributes' =>
		array (
				'placeholder' => '',
				'maxlength' => '255',
		),
		'#default_value' => isset($data->sale_price)?$data->sale_price:"",
);


/*$default = !empty($form_state['values']['howmany_select']) ? $form_state['values']['howmany_select'] : 1;

$form['howmany_select'] = array(
		'#title' => t('How many checkboxes do you want?'),
		'#type' => 'select',
		'#options' => array(1 => 1, 2 => 2, 3 => 3, 4 => 4),
		'#default_value' => $default,
		'#ajax' => array(
				'callback' => 'ajax_example_autocheckboxes_callback',
				'wrapper' => 'checkboxes-div',
				'method' => 'replace',
				'effect' => 'fade',
		),

);


$form['checkboxes_fieldset'] = array(
		'#title' => t("Generated Checkboxes"),
		// The prefix/suffix provide the div that we're replacing, named by
		// #ajax['wrapper'] above.
		'#prefix' => '<div id="checkboxes-div">',
		'#suffix' => '</div>',
		'#type' => 'fieldset',
		'#description' => t('This is where we get automatically generated checkboxes'),
);

$num_checkboxes = !empty($form_state['values']['howmany_select']) ? $form_state['values']['howmany_select'] : 1;
for ($i = 1; $i <= $num_checkboxes; $i++) {
	$form['checkboxes_fieldset']["checkbox$i"] = array(
			'#type' => 'checkbox',
			'#title' => "Checkbox $i",
	);
}
*/

$form['submit']=array('#type'=>'submit','#value'=>'Save');
return $form;
}
function st_price_validate($form,&$form_state){

}
function st_price_add_submit($form,&$form_state){
global $user;
$query = db_insert('st_price')
	 ->fields(array('mid'=>$form_state['values']['mid'],'unit_price'=>$form_state['values']['unit_price'],'total_price'=>$form_state['values']['total_price'],'base_price'=>$form_state['values']['base_price'],'sale_price'=>$form_state['values']['sale_price'],'created'=>strtotime($form_state['values']['created']),'updated'=>strtotime($form_state['values']['updated']),'updatedby'=>$form_state['values']['updatedby'],'createdby'=>$form_state['values']['createdby'],'deleted'=>$form_state['values']['deleted'],))->execute();
if($query>0){
    	drupal_set_message('st_price added successfully');
		drupal_goto('admins/st_price/view');	
    }
}
function st_price_edit_submit($form,&$form_state){
global $user;
$query = db_update('st_price')
	 ->fields(array('mid'=>$form_state['values']['mid'],'unit_price'=>$form_state['values']['unit_price'],'total_price'=>$form_state['values']['total_price'],'base_price'=>$form_state['values']['base_price'],'sale_price'=>$form_state['values']['sale_price'],'created'=>strtotime($form_state['values']['created']),'updated'=>strtotime($form_state['values']['updated']),'updatedby'=>$form_state['values']['updatedby'],'createdby'=>$form_state['values']['createdby'],'deleted'=>$form_state['values']['deleted'],))
	 ->condition('id', $form_state['values']['id'], '=')
	 ->execute();
if($form_state['values']['id']>0){
    	drupal_set_message('st_price update successfully');
		drupal_goto('admins/st_price/view');
    }
}
function st_price_view($form,&$form_state){
	$form['html_markup'] = array(
			'#markup' => t(
					'<a href="http://shardatraders.com/admins/st_price/add">Add Price</a>'
					)
	);
global $user;
	$query = db_select('st_price','tn')
	->extend('PagerDefault')
	->fields('tn')
	->orderBy('tn.pri_id','desc')
	->limit(20);
	$result = $query->execute();
$rows_articles=array();
foreach ($result as $records){
/* $created=util_date_format_short($records->created);
$updated=util_date_format_short($records->updated);
if($records->deleted){
			 $deleted="Deleted";
            }
		else
		{
		//	$deleted=l("<i class='icon-fixed-width icon-trash'></i>Delete",'admins/st_price/edit/'.$records->,array('html'=>TRUE));
		} */
$rows_articles[] = array($records->pri_id,$records->mid,$records->unit_price,$records->total_price,$records->base_price,$records->sale_price);
}
$headers=array('Pri_id','Mid','Unit Price','Total Price','Base Price','Sale Price');
$all_articles=theme('table', array('header' => $headers, 'rows' => $rows_articles,'empty'=>'No Record Found','attributes'=>array('class'=>array('list-table'),'style'=>'width:100%;')));
$all_articles .=theme('pager');
$form['all_articles']=array(
			'#markup'=>$all_articles,
	);
return $form;
}
function st_price_detail($form,&$form_state,$id=NULL){
global $user;
	$query = db_select('st_price','tn')
	->extend('PagerDefault')
	->fields('tn')
	->condition('tn.id',$id,'=')
	->orderBy('tn.id','desc');
	$result = $query->execute()->fetchObject();
$rows_articles=array();
if(!empty($result))
foreach ($result as $key => $value){



$rows_articles[] = array($key.' :: '.$value);
}

$all_articles=theme('table', array('header' => array(), 'rows' => $rows_articles,'empty'=>'No Record Found','attributes'=>array('class'=>array('list-table'),'style'=>'width:100%;')));
$all_articles .=theme('pager');
$form['all_articles']=array(
			'#markup'=>$all_articles,
	);
return $form;
}
function ajax_example_autocheckboxes_callback1($form, $form_state) {
	return $form['checkboxes_fieldset'];
}

