<?php 
function st_material_category_permission(){
array (
  'st_material_category_per_add' => 
  array (
    'title' => 'Create form st_material_category According To choice',
    'description' => 'Form st_material_category Creation',
  ),
  'st_material_category_per_view' => 
  array (
    'title' => 'View The List Of st_material_category',
    'description' => 'View st_material_category according to his powers',
  ),
);
}
function st_material_category_menu() {
$items['admins/st_material_category/add']=array (
  'title' => 'Add New St Material Category Form',
  'page callback' => 'drupal_get_form',
  'page arguments' => 
  array (
    0 => 'st_material_category_add',
  ),
  'access arguments' => 
  array (
    0 => 'st_material_category_per_add',
  ),
  'description' => 'General',
  'type' => 0,
  'weight' => 1,
);
$items['admins/st_material_category/view']=array (
  'title' => 'St Material Category List',
  'page callback' => 'drupal_get_form',
  'page arguments' => 
  array (
    0 => 'st_material_category_view',
  ),
  'access arguments' => 
  array (
    0 => 'st_material_category_per_view',
  ),
  'description' => 'General',
  'type' => 0,
  'weight' => 1,
);
$items['admins/st_material_category/edit/%']=array (
  'title' => 'St Material Category Edit',
  'page callback' => 'drupal_get_form',
  'page arguments' => 
  array (
    0 => 'st_material_category_add',
    1 => 3,
  ),
  'access arguments' => 
  array (
    0 => 'st_material_category_per_add',
  ),
  'description' => 'General',
  'type' => 0,
  'weight' => 1,
);
$items['admins/st_material_category/detail/%']=array (
  'title' => 'St Material Category detail',
  'page callback' => 'drupal_get_form',
  'page arguments' => 
  array (
    0 => 'st_material_category_detail',
    1 => 3,
  ),
  'access arguments' => 
  array (
    0 => 'st_material_category_per_view',
  ),
  'description' => 'General',
  'type' => 0,
  'weight' => 1,
);
return $items;
}
function st_material_category_add($form,&$form_state,$id=NULL){
	 
 if(!empty($id)){
		$data = get_data_by_pks('st_material_category', $id);
		
		$form['#submit'][] = "st_material_category_edit_submit";
		$form['id']=array(
				'#type'=>'value',
				'#value'=>$id,
		);
	}	
$form['material_category']=array (
  '#type' => 'textfield',
  '#title' => 'Material Category Name',
  '#size' => '255',
  '#attributes' => 
  array (
    'placeholder' => '',
    'maxlength' => '255',
  ),
  '#default_value' => isset($data->material_category)?$data->material_category:"",
);
$form['is_parent']=array (
  '#type' => 'select',
  '#title' => 'Is_parent',
  //'#size' => '255',
	'#options'=>parents_cat(),
  /* '#attributes' => 
  array (
    'placeholder' => '',
    'maxlength' => '255',
  ), */
  '#default_value' => isset($data->is_parent)?$data->is_parent:"",
);/* 
$form['created']=array (
  '#type' => 'textfield',
  '#title' => 'Created',
  '#size' => '10',
  '#attributes' => 
  array (
    'placeholder' => '',
    'maxlength' => '10',
  ),
  '#default_value' => isset($data->created)?date("Y-m-d",$data->created):"",
);
$form['updated']=array (
  '#type' => 'textfield',
  '#title' => 'Updated',
  '#size' => '10',
  '#attributes' => 
  array (
    'placeholder' => '',
    'maxlength' => '10',
  ),
  '#default_value' => isset($data->updated)?date("Y-m-d",$data->updated):"",
);
$form['updatedby']=array (
  '#type' => 'textfield',
  '#title' => 'Updatedby',
  '#size' => '10',
  '#attributes' => 
  array (
    'placeholder' => '',
    'maxlength' => '10',
  ),
  '#default_value' => isset($data->updatedby)?$data->updatedby:"",
);
$form['createdby']=array (
  '#type' => 'textfield',
  '#title' => 'Createdby',
  '#size' => '10',
  '#attributes' => 
  array (
    'placeholder' => '',
    'maxlength' => '10',
  ),
  '#default_value' => isset($data->createdby)?$data->createdby:"",
);
$form['deleted']=NULL; */

$form['submit']=array('#type'=>'submit','#value'=>'Save');
return $form;
}
function st_material_category_validate($form,&$form_state){

}
function st_material_category_add_submit($form,&$form_state){
global $user;
$query = db_insert('st_material_category')
	 ->fields(array('material_category'=>$form_state['values']['material_category'],
	 		'is_parent'=>$form_state['values']['is_parent'],
	 		/* 'created'=>strtotime($form_state['values']['created']),
	 		'updated'=>strtotime($form_state['values']['updated']),
	 		'updatedby'=>$form_state['values']['updatedby'],
	 		'createdby'=>$form_state['values']['createdby'],
	 		'deleted'=>$form_state['values']['deleted'], */
	 		
	 )
	 		)->execute();
if($query>0){
    	drupal_set_message('st_material_category added successfully');
		drupal_goto('admins/st_material_category/view');	
    }
}
function st_material_category_edit_submit($form,&$form_state){
global $user;
$query = db_update('st_material_category')
	 ->fields(array('material_category'=>$form_state['values']['material_category'],'is_parent'=>$form_state['values']['is_parent'],'created'=>strtotime($form_state['values']['created']),'updated'=>strtotime($form_state['values']['updated']),'updatedby'=>$form_state['values']['updatedby'],'createdby'=>$form_state['values']['createdby'],'deleted'=>$form_state['values']['deleted'],))
	 ->condition('id', $form_state['values']['id'], '=')
	 ->execute();
if($form_state['values']['id']>0){
    	drupal_set_message('st_material_category update successfully');
		drupal_goto('admins/st_material_category/view');
    }
}
function st_material_category_view($form,&$form_state){
	$form['html_markup'] = array(
			'#markup' => t(
					'<a href="http://shardatraders.com/admins/st_material_category/add">Add Category</a>'
					)
	);
	
global $user;
	$query = db_select('st_material_category','tn')
	->extend('PagerDefault')
	->fields('tn')
	->orderBy('tn.cid','desc')
	->limit(20);
	$result = $query->execute();
$rows_articles=array();
foreach ($result as $records){
/* $created=util_date_format_short($records->created);
$updated=util_date_format_short($records->updated);
if($records->deleted){
			 $deleted="Deleted";
            }
		else
		{
			//$deleted=l("<i class='icon-fixed-width icon-trash'></i>Delete",'admins/st_material_category/edit/'.$records->,array('html'=>TRUE));
		} */
$rows_articles[] = array($records->cid,$records->material_category,$records->is_parent);
}
$headers=array('Cid','Material Category','Is_parent');
$all_articles=theme('table', array('header' => $headers, 'rows' => $rows_articles,'empty'=>'No Record Found','attributes'=>array('class'=>array('list-table'),'style'=>'width:100%;')));
$all_articles .=theme('pager');
$form['all_articles']=array(
			'#markup'=>$all_articles,
	);
return $form;
}
function st_material_category_detail($form,&$form_state,$id=NULL){
global $user;
	$query = db_select('st_material_category','tn')
	->extend('PagerDefault')
	->fields('tn')
	->condition('tn.id',$id,'=')
	->orderBy('tn.id','desc');
	$result = $query->execute()->fetchObject();
$rows_articles=array();
if(!empty($result))
foreach ($result as $key => $value){



$rows_articles[] = array($key.' :: '.$value);
}

$all_articles=theme('table', array('header' => array(), 'rows' => $rows_articles,'empty'=>'No Record Found','attributes'=>array('class'=>array('list-table'),'style'=>'width:100%;')));
$all_articles .=theme('pager');
$form['all_articles']=array(
			'#markup'=>$all_articles,
	);
return $form;
}
function parents_cat(){
	   $par=array();
		$parent_cat=db_query("SELECT material_category from st_material_category")->fetchAll();
		//echo "<pre>";
	//print_r($parent_cat[0]->material_category);
	foreach($parent_cat as $res){
		//print_r($res);
		$par['0']='select';
		$par[]=$res->material_category;
		
	}	
	
	return $par;
}